@startuml Documento grafico
class Documento_grafico{

}
class Hojas{

}
class Dibujo{

}
class texto{

}
class figura_2D{

}
class grupo{
    
}
class circulo{

}
class cuadrado{

}

Documento_grafico *-- Hojas
Dibujo -- Hojas
Dibujo <|-- texto
Dibujo <|-- figura_2D
Dibujo <|-- grupo
grupo "2..*" o-- Dibujo
figura_2D <|-- circulo
figura_2D <|-- cuadrado


@enduml