@startuml Reto04
class Equipo_voleyball{
    + Nombre : string 
    + Registro : int 
}
class Persona{
    + Telefono : int
    + Nombre : string
    # Direccion : string 
}
class Entrenador{
    + Nivel_acreditacion : int
    + Num_años_experiencia : int

}
class Jugador{
    + Numero : int 
    + Posicion : string 

}
class Juegos{
    + Localidad : string 
    + Puntuacion : int

}
Equipo_voleyball "0.1" -- "0.*" Entrenador
Equipo_voleyball "6..20" -- Jugador : tiene
Persona <|-- Entrenador
Persona <|-- Jugador
Equipo_voleyball -- "1.*" Juegos : compite




object ": Equipo_voleyball" as o3
o3 : Nombre = voy
o3 : Registro = no se que es 

object "Capitan : Jugador" as o1
o1 : Telefono = 4141158477
o1 : Nombre = voy 
o1 : Direccion = voy
o1 : Numero = 7
o1 : Posicion = delantero


object ": Entrenador" as o2
o2 : Telefono = 4141158477
o2 : Nombre = voy 
o2 : Direccion = voy
o2 : Nivel_acreditacion = 5
o2 : Num_años_experiencia = 5

object "VZLA vs COL : Juegos" as o4
o4 : Localidad = Panamericanos, Chile 
o4 : Puntuacion = 4-0


o3 -- o1
o3 - o2
o3 -- o4

@enduml